{{- if .Values.logsvrConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-logsvr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-logsvr"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  application.yaml: |-
    spring:
      application:
        name: {{ include "common.names.fullname" . }}-logsvr
      data:
        mongodb:
          {{ if .Values.externalMongoDB.existingPasswordSecret }}
          uri: mongodb://{{ include "job.mongodb.username" . }}:{{- .Values.externalMongoDB.existingPasswordKey | default "mongodb-password" | printf "${%s}" }}@{{- include "job.mongodb.host" . }}:{{- include "job.mongodb.port" . }}/{{- include "job.mongodb.database" . }}
          {{- else -}}
          uri: mongodb://{{ include "job.mongodb.username" . }}:${mongodb-password}@{{- include "job.mongodb.host" . }}:{{- include "job.mongodb.port" . }}/{{- include "job.mongodb.database" . }}
          {{- end }}
    job:
      logsvr:
        mongodb:
          shard:
            enabled: false
    server:
      port: {{ .Values.logsvrConfig.containerPort }}
  {{- end}}
