apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-logsvr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-logsvr"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.logsvrConfig.autoscaling.enabled }}
  replicas: {{ .Values.logsvrConfig.replicaCount }}
  {{- end }}
  selector:
    matchLabels: 
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: job-logsvr
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: "job-logsvr"
    spec:
      {{- include "job.imagePullSecrets" . | nindent 6 }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- if .Values.logsvrConfig.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.logsvrConfig.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.logsvrConfig.podAffinityPreset "component" "job-logsvr" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.logsvrConfig.podAntiAffinityPreset "component" "job-logsvr" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.logsvrConfig.nodeAffinityPreset.type "key" .Values.logsvrConfig.nodeAffinityPreset.key "values" .Values.logsvrConfig.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.logsvrConfig.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.logsvrConfig.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.logsvrConfig.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.logsvrConfig.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.logsvrConfig.priorityClassName }}
      priorityClassName: {{ .Values.logsvrConfig.priorityClassName | quote }}
      {{- end }}
      serviceAccountName: {{ include "job.serviceAccountName" . | quote }}
      {{- if .Values.logsvrConfig.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.logsvrConfig.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: "job-logsvr"
          {{- if .Values.logsvrConfig.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.logsvrConfig.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: {{ include "job-logsvr.image" . }}
          imagePullPolicy: {{ .Values.logsvrConfig.image.pullPolicy }}
          env:
            - name: BK_JOB_JVM_OPTION
              value: "-Xms512m -Xmx512m -XX:NewRatio=1 -XX:SurvivorRatio=8 "
            - name: BK_JOB_PROFILE
              value: {{ include "job.profile" . }}
            - name: BK_JOB_JAR
              value: job-logsvr.jar
            - name: BK_JOB_LOG_BASE_DIR
              value: /data/logs/job
            - name: BK_JOB_LOG_DIR
              value: /data/logs/job/job-logsvr
            - name: JOB_APPLICATION_CONFIGMAP_NAME
              value: {{ include "common.names.fullname" . }}-logsvr
            - name: JOB_COMMON_CONFIGMAP_NAME
              value: {{ include "common.names.fullname" . }}-common
            - name: spring_cloud_kubernetes_secrets_paths
              value: /etc/secrets
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: {{ .Values.logsvrConfig.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          resources:
            {{- toYaml .Values.logsvrConfig.resources | nindent 12 }}
          volumeMounts:
            - name: mariadb
              mountPath: /etc/secrets/mariadb
              readOnly: true
            - name: rabbitmq
              mountPath: /etc/secrets/rabbitmq
              readOnly: true
            - name: redis
              mountPath: /etc/secrets/redis
              readOnly: true
      volumes:
        - name: mariadb
          secret:
            secretName: {{ include "job.mariadb.secretName" . }}
        - name: rabbitmq
          secret:
            secretName: {{ include "job.rabbitmq.secretName" . }}-map
        - name: redis
          secret:
            secretName: {{ include "job.redis.secretName" . }}

