apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-migration"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: "job-migration"
    spec:
      containers:
        - name: "job-migration"
          image: {{ include "job-migration.image" . }}
          env:
            - name: BK_JOB_MYSQL_HOST
              value: {{- include "job.mariadb.host" . }}
            - name: BK_JOB_MYSQL_PORT
              value: {{- include "job.mariadb.port" . }}
            - name: BK_JOB_MYSQL_ROOT_PASSWORD
              value: {{- .Values.mariadb.auth.rootPassword }}
          command: ["bash"]
          args: ["/data/job/startup.sh"]
      restartPolicy: Never
