{{- if .Values.job.monitor.collectEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bk-job
spec:
  endpoints:
    - basicAuth:
        password:
          name: {{ include "common.names.fullname" . }}-actuator-basic-auth
          key: password
        username:
          name: {{ include "common.names.fullname" . }}-actuator-basic-auth
          key: user
    - interval: 3s # 采集周期
      path: /actuator/prometheus # 指标接口路径
      port: http # service的端口名，必须使用端口名，不能使用数字
  namespaceSelector:
    any: true
  selector: # 过滤出需要采集的service
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
      {{ include "job.labelKeys.jobScope" . }}: {{ include "job.labelValues.jobScope.backend" . }}
{{- end }}
