apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bk-job-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.job.pv.storage }}
