apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-actuator-basic-auth
data:
  user: {{ .Values.job.actuator.user.name }}
  password: {{ .Values.job.actuator.user.password }}
type: Opaque
