apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ingress-tls" .Values.gatewayConfig.ingress.hostname }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | indent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls:
    crt: {{ .Files.Get "cert/job_server.crt" | b64enc }}
    key: {{ .Files.Get "cert/job_server.key" | b64enc }}
