spring:
  application:
    name: job-crontab
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource
  datasource:
    job-crontab:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://__BK_JOB_CRONTAB_MYSQL_HOST__:__BK_JOB_CRONTAB_MYSQL_PORT__/job_crontab?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: __BK_JOB_CRONTAB_MYSQL_USERNAME__
      password: __BK_JOB_CRONTAB_MYSQL_PASSWORD__
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      poolName: "job-crontab"
      validationTimeout: 5000
  rabbitmq:
    host: __BK_JOB_CRONTAB_RABBITMQ_HOST__
    port: __BK_JOB_CRONTAB_RABBITMQ_PORT__
    username: __BK_JOB_CRONTAB_RABBITMQ_USERNAME__
    password: __BK_JOB_CRONTAB_RABBITMQ_PASSWORD__
    virtual-host: __BK_JOB_CRONTAB_RABBITMQ_VHOST__
  redis:
    host: __BK_JOB_CRONTAB_REDIS_HOST__
    port: __BK_JOB_CRONTAB_REDIS_PORT__
    sentinel:
      password: __BK_JOB_CRONTAB_REDIS_SENTINEL_PASSWORD__
      master: __BK_JOB_CRONTAB_REDIS_SENTINEL_MASTER__
      nodes: __BK_JOB_CRONTAB_REDIS_SENTINEL_NODES__
    password: __BK_JOB_CRONTAB_REDIS_PASSWORD__
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  quartz:
    thread-pool:
      thread-name-prefix: QuartzThreadPoolTaskExecutor-
      thread-priority: 5
      daemon: false
      thread-group-name: QuartzThreadPoolTaskExecutorGroup
      core-pool-size: 150
      max-pool-size: 300
      keep-alive-seconds: 60
      queue-capacity: 150
      allow-core-thread-timeout: false
      waitfor-tasks-tocomplete-onshutdown: true
      await-termination-seconds: 900
    scheduler:
      config-location: classpath:quartz.properties
      scheduler-name: quartz-scheduler
      application-context-scheduler-contextkey: applicationContext
      overwrite-existing-jobs: true
      auto-startup: true
      startup-delay: 10
    properties:
      org:
        quartz:
          scheduler:
            batchTriggerAcquisitionMaxCount: 150
          threadPool:
            threadCount: 150
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 10000
  eureka:
    enabled: false
job:
  crontab:
    db:
      url: jdbc:mysql://__BK_JOB_CRONTAB_MYSQL_HOST__:__BK_JOB_CRONTAB_MYSQL_PORT__/job_crontab?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: __BK_JOB_CRONTAB_MYSQL_USERNAME__
      password: __BK_JOB_CRONTAB_MYSQL_PASSWORD__

