spring:
  application:
    name: job-logsvr
  profiles:
    active: prod
  cloud:
    consul:
      discovery:
        service-name: 'job-logsvr'
        instance-id: job-logsvr-${machine.ip}-${server.port}
        enabled: true
        prefer-ip-address: false
  data:
    mongodb:
      uri: __BK_JOB_LOGSVR_MONGODB_URI__
job:
  logsvr:
    mongodb:
      shard:
        enabled: true
server:
  port: __BK_JOB_LOGSVR_SERVER_PORT__
