spring:
  application:
    name: job-file-gateway
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource
  datasource:
    job-file-gateway:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://__BK_JOB_FILE_GATEWAY_MYSQL_HOST__:__BK_JOB_FILE_GATEWAY_MYSQL_PORT__/job_file_gateway?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: __BK_JOB_FILE_GATEWAY_MYSQL_USERNAME__
      password: __BK_JOB_FILE_GATEWAY_MYSQL_PASSWORD__
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      poolName: "job-file-gateway"
      validationTimeout: 5000
  redis:
    host: __BK_JOB_FILE_GATEWAY_REDIS_HOST__
    port: __BK_JOB_FILE_GATEWAY_REDIS_PORT__
    mode: __BK_JOB_FILE_GATEWAY_REDIS_MODE__
    # 使用Redis Sentinel时的配置项
    sentinel:
      password: __BK_JOB_FILE_GATEWAY_REDIS_SENTINEL_PASSWORD__
      master: __BK_JOB_FILE_GATEWAY_REDIS_SENTINEL_MASTER__
      nodes: __BK_JOB_FILE_GATEWAY_REDIS_SENTINEL_NODES__
    password: __BK_JOB_FILE_GATEWAY_REDIS_PASSWORD__
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

