{{- if .Values.gatewayConfig.ingress.https.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-gateway-ingress-tls
  namespace: default
data:
  tls.crt: {{ .Values.gatewayConfig.ingress.https.certBase64 }}
  tls.key: {{ .Values.gatewayConfig.ingress.https.keyBase64 }}
type: kubernetes.io/tls
{{- end }}
